### ISSUE TITLE
Possible minor typo in the paper.

### ISSUE THREAD

**Issue by kdexd** [layer6ai-labs/T-Fixup#2]
Hi, thanks for releasing the code, and great paper with strong results! This is not directly related to the codebase — I spotted a possible typo in the paper ([ICML 2020 pre-proceedings](https://proceedings.icml.cc/static/paper_files/icml/2020/5691-Paper.pdf)). Equation 3 here should have a + sign in the braces since `(- $\eta$)` is taken common outside?

![image](https://user-images.githubusercontent.com/10494087/87861621-08a95500-c916-11ea-9766-65f3ab649bdf.png)

Please correct me if I am wrong, or missing something here.

**Comment by risingdhxs** [comment]
Yes, thank you for pointing it out. We will correct it in the camera ready version.
