### ISSUE TITLE
T-Fixup for Language Modeling

### ISSUE THREAD

**Issue by sairams-intel** [layer6ai-labs/T-Fixup#6]
Hello, thanks for sharing the code! Have you tried the T-Fixup initialization on language modeling tasks, in transformer models like BERT? Since the decoder is absent, I was wondering if you have any suggestions on how to initialize the encoder so as to remove layer norm as shown in this paper?

**Comment by gaceladri** [comment]
I am looking for the same. The reason to close the issue without answering is that it is the same initialization for encoder only models or..?
